// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCzbBITKhbLy-2l7IIiw40fl_-PdBawYBI',
    appId: '1:368190423136:web:bdd3d78f8e43be97160305',
    messagingSenderId: '368190423136',
    projectId: 'demoz-9ac38',
    authDomain: 'demoz-9ac38.firebaseapp.com',
    storageBucket: 'demoz-9ac38.appspot.com',
    measurementId: 'G-K34CBD9VRZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAw8ERn5my0J57vuvf0E8gz2T6OFrNjDeI',
    appId: '1:368190423136:android:88149af7f8150a26160305',
    messagingSenderId: '368190423136',
    projectId: 'demoz-9ac38',
    storageBucket: 'demoz-9ac38.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCSzoID0AyKtOhJvxXurzyFFM6OayuqvmQ',
    appId: '1:368190423136:ios:35cdba49d66d5360160305',
    messagingSenderId: '368190423136',
    projectId: 'demoz-9ac38',
    storageBucket: 'demoz-9ac38.appspot.com',
    iosBundleId: 'com.example.demozApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCSzoID0AyKtOhJvxXurzyFFM6OayuqvmQ',
    appId: '1:368190423136:ios:35cdba49d66d5360160305',
    messagingSenderId: '368190423136',
    projectId: 'demoz-9ac38',
    storageBucket: 'demoz-9ac38.appspot.com',
    iosBundleId: 'com.example.demozApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCzbBITKhbLy-2l7IIiw40fl_-PdBawYBI',
    appId: '1:368190423136:web:efc6128d083e8360160305',
    messagingSenderId: '368190423136',
    projectId: 'demoz-9ac38',
    authDomain: 'demoz-9ac38.firebaseapp.com',
    storageBucket: 'demoz-9ac38.appspot.com',
    measurementId: 'G-M3QDMW6MDW',
  );
}
